version: "3"

services:
  cashier:
    image: spring-cashier
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    environment:
      STARBUCKS_API_HOST: kong
      STARBUCKS_API_PORT: 80
      KONG_ENABLED: true
      KONG_API_KEY: 2H3fONTa8ugl1IcVS7CjLPnPIS2Hp9dJ
    ports:
      - 9090:9090
    restart: always

  kong:
    image: kong:2.4.0
    platform: linux/amd64
    depends_on:
    - starbucks-api
    networks:
      - network     
    restart: always  
    ports:
    - "80:8000"
    - "443:8443"
    - "8001:8001"
    - "8444:8444"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001, 0.0.0.0:8444 ssl"

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    networks:
      - network
    ports:
      - "3306:3306"   
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
      MYSQL_DATABASE: "starbucks"
    restart: always
    
  starbucks-api:
    image: spring-starbucks-api
    platform: linux/amd64
    depends_on:
    - mysql    
    networks:
      - network   
    ports:
      - "8080:8080"    
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASS: "cmpe172"
    restart: always     

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

