apiVersion: v1
kind: Service
metadata:
  name: background-worker-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 80 
    targetPort: 8080
    protocol: TCP
  selector:
    name: background-worker