version: "3"

services:
  mysql:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - /tmp:/tmp
    networks:
      - network
    environment:
      MYSQL_ROOT_PASSWORD: "cmpe172"
      MYSQL_DATABASE: "midterm"
      MYSQL_USER: "dbuser"
      MYSQL_PASS: "dbapss"
    restart: always
    ports:
      - "3306:3306"
  cashier:
    image: spring-cashier
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - /tmp:/tmp
    networks:
      - network
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASS: "cmpe172"
    ports:
      - 9090
    restart: always
  lb:
    image: eeacms/haproxy
    platform: linux/amd64
    depends_on:
      - cashier
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      BACKENDS: "cashier"
      BACKENDS_PORT: "9090"
      DNS_ENABLED: "true"
      COOKIES_ENABLED: "true"
      LOG_LEVEL: "info"
    networks:
      - network

volumes:
  schemas:
    external: false

networks:
  network:
    driver: bridge

